name: game_prototype_simulator
description: "A simulator for game design, which makes it easy to create and test game prototypes."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  mocktail: ^1.0.4
  injectable: ^2.5.0
  get_it: ^8.0.3
  rxdart: ^0.28.0
  provider: ^6.1.2
  flutter_colorpicker: ^1.1.0
  drift: ^2.25.0
  drift_flutter: ^0.2.4
  go_router: ^14.8.0
  intl: any
  sqlite3_flutter_libs: ^0.5.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  injectable_generator: ^2.6.2
  drift_dev: ^2.25.0
  go_router_builder: ^2.8.0

flutter:
  uses-material-design: true
  generate: true